version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "composer.json" }}
      - run: composer global require bamarni/composer-bin-plugin
      - run: composer bin phpstan require phpstan/phpstan "^0.11.5"
      - run: composer bin phpcs require squizlabs/php_codesniffer "^3.4"
      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
            - ./vendor-bin
          key: dependencies-cache-{{ checksum "composer.json" }}
  test:
    docker:
      - image: circleci/php:7.2-browsers
    steps:
      - checkout
      - run: php vendor/bin/phpcs
      - run: php vendor/bin/phpstan analyse src tests -l 1
      - run: php vendor/bin/phpunit tests/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master